channels:
- defaults
- conda-forge
dependencies:
 - python=3.5
 - numpy
 - scipy
 - scikit-learn
 - jupyter
 - requests
 - pandas
 - seaborn
 - click
 - openpyxl
 - matplotlib
 - pip:
  - watermark
  - pytest